kind: pipeline
type: docker
name: Telegram Downloader Build
workspace:
  path: /drone/src
steps:
 - name: Build Exe
   image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
   volumes:
     - name: publish
       path: /publish
   commands:
    - dotnet publish /drone/src/TelegramGroupFileDownloader/TelegramGroupFileDownloader.csprj --output /publish --runtime linux-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesInSingleFile=true --configuration Release
    - dotnet publish /drone/src/TelegramGroupFileDownloader/TelegramGroupFileDownloader.csprj --output /publish --runtime win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesInSingleFile=true --configuration Release
#  - name: Deploy Site
#    image: mcr.microsoft.com/azure-cli
#    volumes:
#      - name: resume
#        path: /build
#    environment:
#      CONNECTION:
#        from_secret: connection-string
#    commands:
#      - az storage blob upload-batch --destination '$web' --source /build/ --connection-string $CONNECTION
volumes:
  - name: publish
    temp: {}