//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weekenders.TelegramDownloader.Ui {
    using System;
    using Terminal.Gui;
    
    
    public partial class Ui : Window
    {
        private FrameView _logView;
        private FrameView _statsView;
        private MenuBar _menuBar;
        private static void InitializeMainWindow(Window window)
        {
            window.Width = Dim.Fill(0);
            window.Height = Dim.Fill(0);
            window.X = 0;
            window.Y = 0;
            window.Text = "";
            window.Border.BorderStyle = BorderStyle.None;
            window.Border.BorderBrush = Color.Blue;
            window.Border.Effect3D = false;
            window.TextAlignment = TextAlignment.Left;
            window.Title = null;
        }

        private static FrameView InitializeLogWindow()
        {
            var logView = new FrameView();
            logView.Width = Dim.Percent(80);
            logView.Height = Dim.Fill(0);
            logView.X = 0;
            logView.Y = 1;
            logView.Data = "LogView";
            logView.Text = "Log View Placeholder";
            logView.Border.BorderStyle = BorderStyle.Single;
            logView.Border.BorderBrush = Color.BrightYellow;
            logView.Border.Effect3D = false;
            logView.TextAlignment = TextAlignment.Left;
            return logView;
        }
        private static FrameView InitializeStatsWindow()
        {
            var statsView = new FrameView();
            statsView.Width = Dim.Percent(20);
            statsView.Height = Dim.Fill(0);
            statsView.X = 80;
            statsView.Y = 1;
            statsView.Data = "LogView";
            statsView.Text = "Log View Placeholder";
            statsView.Border.BorderStyle = BorderStyle.Single;
            statsView.Border.BorderBrush = Color.BrightYellow;
            statsView.Border.Effect3D = false;
            statsView.TextAlignment = TextAlignment.Left;
            return statsView;
        }

        private static MenuBar InitializeMenuBar()
        {
            var menu = new MenuBar();
            menu.Width = Dim.Fill(0);
            menu.Height = 1;
            menu.X = 0;
            menu.Y = 0;
            menu.Data = "menubar1";
            menu.Text = "";
            menu.TextAlignment = TextAlignment.Left;
            var file = new MenuBarItem();
            file.Title = "_File (F9)";
            var item1 = new MenuItem();
            item1.Title = "_Do Something";
            file.Children = new MenuItem[] {
                item1};
            menu.Menus = new MenuBarItem[] {
                file};
            return menu;
        }
        
        private void InitializeComponent() {
            InitializeMainWindow(this);
            _menuBar = InitializeMenuBar();
            Add(_menuBar);
            _logView = InitializeLogWindow();
            Add(_logView);
            _statsView = InitializeStatsWindow();
            Add(_statsView);
        }
    }
}
